// Generated by tools/build_fixture_songs.py — do not edit by hand.
//
// The lyric documents are inlined as strings rather than shipped as asset files
// on purpose. SPEC §3 is explicit that no network call and nothing slow may sit
// between the play button and the first beat; text that is already in the JS
// bundle cannot be late. It also sidesteps teaching Metro about a `.elrc`
// extension for what is, in Phase 1, three fixture songs.
//
// Audio stays an asset — a megabyte of AAC has no business in a JS bundle — and
// is wired up in `bundled.ts`, where `require()` can take a literal path.

import type { LyricVariant } from '@/lyrics/elrc/types';

export interface GeneratedFixture {
  readonly slug: string;
  readonly title: string;
  readonly artist: string;
  readonly language: string;
  readonly genre: readonly string[];
  readonly mood: readonly string[];
  readonly bpm: number;
  readonly musicalKey: string;
  readonly durationMs: number;
  readonly audioChecksum: string;
  readonly lineCount: number;
  readonly lyrics: Readonly<Record<LyricVariant, string>>;
}

export const GENERATED_FIXTURES: readonly GeneratedFixture[] = [
  {
    slug: "kaabo-si-ile",
    title: "Káàbọ̀ Sí Ilé",
    artist: "Afro-Genie Fixture Band",
    language: "yor",
    genre: ["afrobeats"],
    mood: ["warm", "celebratory"],
    bpm: 108,
    musicalKey: "F minor",
    durationMs: 60000,
    audioChecksum: "sha256:f47e6ad8ac7b52f5dfc1fa728edfcef8790ff34374bd52f89260654406a70ff1",
    lineCount: 15,
    lyrics: {
      original: `[ti:Káàbọ̀ Sí Ilé]
[ar:Afro-Genie Fixture Band]
[la:yor]
[var:original]
[length:01:00.000]
[by:Afro-Genie fixture generator — synthesised placeholder, not a release]

[00:08.889]<00:08.889>Ẹ <00:09.306>káàbọ̀ <00:09.861>sí <00:10.278>ilé <00:10.972>
[00:11.111]<00:11.111>Ọ̀rẹ́ <00:11.667>mi <00:12.222>ṣé <00:12.500>o <00:12.778>wà <00:13.194>
[00:13.333]<00:13.333>Mo <00:13.611>ń <00:13.889>lọ <00:14.444>sí <00:14.861>ọjà <00:15.417>
[00:15.556]<00:15.556>Ayọ̀ <00:16.250>wà <00:16.667>nínú <00:17.222>ọkàn <00:17.639>
[00:17.778][bg]<00:17.778>ó <00:18.194>yá <00:18.750>
[00:18.889][break:00:25.556]
[00:25.556]<00:25.556>Ẹ <00:25.972>káàbọ̀ <00:26.528>sí <00:26.944>ilé <00:27.639>
[00:27.778]<00:27.778>Ọ̀rẹ́ <00:28.333>mi <00:28.889>ṣé <00:29.167>o <00:29.444>wà <00:29.861>
[00:30.000]<00:30.000>Mo <00:30.278>ń <00:30.556>lọ <00:31.111>sí <00:31.528>ọjà <00:32.083>
[00:32.222]<00:32.222>Ayọ̀ <00:32.917>wà <00:33.333>nínú <00:33.889>ọkàn <00:34.306>
[00:34.444][bg]<00:34.444>ó <00:34.861>yá <00:35.417>
[00:35.556][break:00:40.000]
[00:40.000]<00:40.000>Ẹ <00:40.417>káàbọ̀ <00:40.972>sí <00:41.389>ilé <00:42.083>
[00:42.222]<00:42.222>Ọ̀rẹ́ <00:42.778>mi <00:43.333>ṣé <00:43.611>o <00:43.889>wà <00:44.306>
[00:44.444]<00:44.444>Mo <00:44.722>ń <00:45.000>lọ <00:45.556>sí <00:45.972>ọjà <00:46.528>
[00:46.667]<00:46.667>Ayọ̀ <00:47.361>wà <00:47.778>nínú <00:48.333>ọkàn <00:48.750>
[00:48.889][bg]<00:48.889>ó <00:49.306>yá <00:49.861>
[00:50.000][break:00:57.778]
`,
      romanised: `[ti:Káàbọ̀ Sí Ilé]
[ar:Afro-Genie Fixture Band]
[la:yor]
[var:romanised]
[length:01:00.000]
[by:Afro-Genie fixture generator — synthesised placeholder, not a release]

[00:08.889]<00:08.889>eh <00:09.306>kaa-baw <00:09.861>see <00:10.278>ee-leh <00:10.972>
[00:11.111]<00:11.111>aw-reh <00:11.667>mee <00:12.222>sheh <00:12.500>oh <00:12.778>wah <00:13.194>
[00:13.333]<00:13.333>moh <00:13.611>n <00:13.889>law <00:14.444>see <00:14.861>aw-jah <00:15.417>
[00:15.556]<00:15.556>ah-yaw <00:16.250>wah <00:16.667>nee-noo <00:17.222>aw-kahn <00:17.639>
[00:17.778][bg]<00:17.778>oh <00:18.194>yah <00:18.750>
[00:18.889][break:00:25.556]
[00:25.556]<00:25.556>eh <00:25.972>kaa-baw <00:26.528>see <00:26.944>ee-leh <00:27.639>
[00:27.778]<00:27.778>aw-reh <00:28.333>mee <00:28.889>sheh <00:29.167>oh <00:29.444>wah <00:29.861>
[00:30.000]<00:30.000>moh <00:30.278>n <00:30.556>law <00:31.111>see <00:31.528>aw-jah <00:32.083>
[00:32.222]<00:32.222>ah-yaw <00:32.917>wah <00:33.333>nee-noo <00:33.889>aw-kahn <00:34.306>
[00:34.444][bg]<00:34.444>oh <00:34.861>yah <00:35.417>
[00:35.556][break:00:40.000]
[00:40.000]<00:40.000>eh <00:40.417>kaa-baw <00:40.972>see <00:41.389>ee-leh <00:42.083>
[00:42.222]<00:42.222>aw-reh <00:42.778>mee <00:43.333>sheh <00:43.611>oh <00:43.889>wah <00:44.306>
[00:44.444]<00:44.444>moh <00:44.722>n <00:45.000>law <00:45.556>see <00:45.972>aw-jah <00:46.528>
[00:46.667]<00:46.667>ah-yaw <00:47.361>wah <00:47.778>nee-noo <00:48.333>aw-kahn <00:48.750>
[00:48.889][bg]<00:48.889>oh <00:49.306>yah <00:49.861>
[00:50.000][break:00:57.778]
`,
      translated: `[ti:Káàbọ̀ Sí Ilé]
[ar:Afro-Genie Fixture Band]
[la:eng]
[var:translated]
[length:01:00.000]
[by:Afro-Genie fixture generator — synthesised placeholder, not a release]

[00:08.889]<00:08.889>Welcome <00:09.861>to <00:10.278>the house <00:10.972>
[00:11.111]<00:11.111>My <00:11.667>friend, <00:12.222>are <00:12.500>you <00:12.778>here? <00:13.194>
[00:13.333]<00:13.333>I <00:13.611>am <00:13.889>going <00:14.444>to <00:14.861>market <00:15.417>
[00:15.556]<00:15.556>Joy <00:16.250>is <00:16.667>in the <00:17.222>heart <00:17.639>
[00:17.778][bg]<00:17.778>let's <00:18.194>go <00:18.750>
[00:18.889][break:00:25.556]
[00:25.556]<00:25.556>Welcome <00:26.528>to <00:26.944>the house <00:27.639>
[00:27.778]<00:27.778>My <00:28.333>friend, <00:28.889>are <00:29.167>you <00:29.444>here? <00:29.861>
[00:30.000]<00:30.000>I <00:30.278>am <00:30.556>going <00:31.111>to <00:31.528>market <00:32.083>
[00:32.222]<00:32.222>Joy <00:32.917>is <00:33.333>in the <00:33.889>heart <00:34.306>
[00:34.444][bg]<00:34.444>let's <00:34.861>go <00:35.417>
[00:35.556][break:00:40.000]
[00:40.000]<00:40.000>Welcome <00:40.972>to <00:41.389>the house <00:42.083>
[00:42.222]<00:42.222>My <00:42.778>friend, <00:43.333>are <00:43.611>you <00:43.889>here? <00:44.306>
[00:44.444]<00:44.444>I <00:44.722>am <00:45.000>going <00:45.556>to <00:45.972>market <00:46.528>
[00:46.667]<00:46.667>Joy <00:47.361>is <00:47.778>in the <00:48.333>heart <00:48.750>
[00:48.889][bg]<00:48.889>let's <00:49.306>go <00:49.861>
[00:50.000][break:00:57.778]
`,
    },
  },
  {
    slug: "sikhona-manje",
    title: "Sikhona Manje",
    artist: "Afro-Genie Fixture Band",
    language: "zul",
    genre: ["amapiano"],
    mood: ["late-night", "hypnotic"],
    bpm: 112,
    musicalKey: "G minor",
    durationMs: 62200,
    audioChecksum: "sha256:071966310e889870470fe81aec6db57c752e9e7976652358d2a230c3f2e3b8f0",
    lineCount: 15,
    lyrics: {
      original: `[ti:Sikhona Manje]
[ar:Afro-Genie Fixture Band]
[la:zul]
[var:original]
[length:01:02.200]
[by:Afro-Genie fixture generator — synthesised placeholder, not a release]

[00:09.643]<00:09.643>Sawubona <00:10.446>mngane <00:11.250>wami <00:11.652>
[00:11.786]<00:11.786>Sikhona <00:12.589>manje <00:13.259>lapha <00:13.795>
[00:13.929]<00:13.929>Ngiyabonga <00:15.000>kakhulu <00:15.938>
[00:16.071]<00:16.071>Hamba <00:16.607>kahle <00:17.411>mngane <00:18.080>
[00:18.214][bg]<00:18.214>yebo <00:18.750>yebo <00:19.152>
[00:19.286][break:00:25.714]
[00:25.714]<00:25.714>Sawubona <00:26.518>mngane <00:27.321>wami <00:27.723>
[00:27.857]<00:27.857>Sikhona <00:28.661>manje <00:29.330>lapha <00:29.866>
[00:30.000]<00:30.000>Ngiyabonga <00:31.071>kakhulu <00:32.009>
[00:32.143]<00:32.143>Hamba <00:32.679>kahle <00:33.482>mngane <00:34.152>
[00:34.286][bg]<00:34.286>yebo <00:34.821>yebo <00:35.223>
[00:35.357][break:00:40.714]
[00:40.714]<00:40.714>Sawubona <00:41.518>mngane <00:42.321>wami <00:42.723>
[00:42.857]<00:42.857>Sikhona <00:43.661>manje <00:44.330>lapha <00:44.866>
[00:45.000]<00:45.000>Ngiyabonga <00:46.071>kakhulu <00:47.009>
[00:47.143]<00:47.143>Hamba <00:47.679>kahle <00:48.482>mngane <00:49.152>
[00:49.286][bg]<00:49.286>yebo <00:49.821>yebo <00:50.223>
[00:50.357][break:01:00.000]
`,
      romanised: `[ti:Sikhona Manje]
[ar:Afro-Genie Fixture Band]
[la:zul]
[var:romanised]
[length:01:02.200]
[by:Afro-Genie fixture generator — synthesised placeholder, not a release]

[00:09.643]<00:09.643>sah-woo-BOH-nah <00:10.446>mm-NGAH-neh <00:11.250>WAH-mee <00:11.652>
[00:11.786]<00:11.786>see-KOH-nah <00:12.589>MAHN-jeh <00:13.259>LAH-pah <00:13.795>
[00:13.929]<00:13.929>ngee-yah-BOH-ngah <00:15.000>kah-KOO-loo <00:15.938>
[00:16.071]<00:16.071>HAHM-bah <00:16.607>KAH-shleh <00:17.411>mm-NGAH-neh <00:18.080>
[00:18.214][bg]<00:18.214>YEH-boh <00:18.750>YEH-boh <00:19.152>
[00:19.286][break:00:25.714]
[00:25.714]<00:25.714>sah-woo-BOH-nah <00:26.518>mm-NGAH-neh <00:27.321>WAH-mee <00:27.723>
[00:27.857]<00:27.857>see-KOH-nah <00:28.661>MAHN-jeh <00:29.330>LAH-pah <00:29.866>
[00:30.000]<00:30.000>ngee-yah-BOH-ngah <00:31.071>kah-KOO-loo <00:32.009>
[00:32.143]<00:32.143>HAHM-bah <00:32.679>KAH-shleh <00:33.482>mm-NGAH-neh <00:34.152>
[00:34.286][bg]<00:34.286>YEH-boh <00:34.821>YEH-boh <00:35.223>
[00:35.357][break:00:40.714]
[00:40.714]<00:40.714>sah-woo-BOH-nah <00:41.518>mm-NGAH-neh <00:42.321>WAH-mee <00:42.723>
[00:42.857]<00:42.857>see-KOH-nah <00:43.661>MAHN-jeh <00:44.330>LAH-pah <00:44.866>
[00:45.000]<00:45.000>ngee-yah-BOH-ngah <00:46.071>kah-KOO-loo <00:47.009>
[00:47.143]<00:47.143>HAHM-bah <00:47.679>KAH-shleh <00:48.482>mm-NGAH-neh <00:49.152>
[00:49.286][bg]<00:49.286>YEH-boh <00:49.821>YEH-boh <00:50.223>
[00:50.357][break:01:00.000]
`,
      translated: `[ti:Sikhona Manje]
[ar:Afro-Genie Fixture Band]
[la:eng]
[var:translated]
[length:01:02.200]
[by:Afro-Genie fixture generator — synthesised placeholder, not a release]

[00:09.643]<00:09.643>Hello <00:10.446>my <00:11.250>friend <00:11.652>
[00:11.786]<00:11.786>We are here <00:12.589>now <00:13.259>in this place <00:13.795>
[00:13.929]<00:13.929>Thank you <00:15.000>very much <00:15.938>
[00:16.071]<00:16.071>Go <00:16.607>well, <00:17.411>friend <00:18.080>
[00:18.214][bg]<00:18.214>yes <00:18.750>yes <00:19.152>
[00:19.286][break:00:25.714]
[00:25.714]<00:25.714>Hello <00:26.518>my <00:27.321>friend <00:27.723>
[00:27.857]<00:27.857>We are here <00:28.661>now <00:29.330>in this place <00:29.866>
[00:30.000]<00:30.000>Thank you <00:31.071>very much <00:32.009>
[00:32.143]<00:32.143>Go <00:32.679>well, <00:33.482>friend <00:34.152>
[00:34.286][bg]<00:34.286>yes <00:34.821>yes <00:35.223>
[00:35.357][break:00:40.714]
[00:40.714]<00:40.714>Hello <00:41.518>my <00:42.321>friend <00:42.723>
[00:42.857]<00:42.857>We are here <00:43.661>now <00:44.330>in this place <00:44.866>
[00:45.000]<00:45.000>Thank you <00:46.071>very much <00:47.009>
[00:47.143]<00:47.143>Go <00:47.679>well, <00:48.482>friend <00:49.152>
[00:49.286][bg]<00:49.286>yes <00:49.821>yes <00:50.223>
[00:50.357][break:01:00.000]
`,
    },
  },
  {
    slug: "how-you-dey",
    title: "How You Dey",
    artist: "Afro-Genie Fixture Band",
    language: "pcm",
    genre: ["highlife"],
    mood: ["bright", "easy"],
    bpm: 96,
    musicalKey: "C major",
    durationMs: 62500,
    audioChecksum: "sha256:4e0bb2d54c536e4088bb7a24f83e2a2e0c0ea38dbb87ed4ab9a07aa35a919bfb",
    lineCount: 15,
    lyrics: {
      original: `[ti:How You Dey]
[ar:Afro-Genie Fixture Band]
[la:pcm]
[var:original]
[length:01:02.500]
[by:Afro-Genie fixture generator — synthesised placeholder, not a release]

[00:08.750]<00:08.750>How <00:09.062>you <00:09.375>dey <00:10.000>my <00:10.312>brother <00:11.094>
[00:11.250]<00:11.250>We <00:11.562>dey <00:12.031>here <00:12.656>well <00:13.125>well <00:13.594>
[00:13.750]<00:13.750>Make <00:14.062>we <00:14.375>go <00:15.000>chop <00:15.469>life <00:16.094>
[00:16.250]<00:16.250>Na <00:16.562>so <00:16.875>e <00:17.188>be <00:17.969>o <00:18.594>
[00:18.750][bg]<00:18.750>ehn <00:19.219>ehn <00:19.844>
[00:20.000][break:00:27.500]
[00:27.500]<00:27.500>How <00:27.812>you <00:28.125>dey <00:28.750>my <00:29.062>brother <00:29.844>
[00:30.000]<00:30.000>We <00:30.312>dey <00:30.781>here <00:31.406>well <00:31.875>well <00:32.344>
[00:32.500]<00:32.500>Make <00:32.812>we <00:33.125>go <00:33.750>chop <00:34.219>life <00:34.844>
[00:35.000]<00:35.000>Na <00:35.312>so <00:35.625>e <00:35.938>be <00:36.719>o <00:37.344>
[00:37.500][bg]<00:37.500>ehn <00:37.969>ehn <00:38.594>
[00:38.750][break:00:43.750]
[00:43.750]<00:43.750>How <00:44.062>you <00:44.375>dey <00:45.000>my <00:45.312>brother <00:46.094>
[00:46.250]<00:46.250>We <00:46.562>dey <00:47.031>here <00:47.656>well <00:48.125>well <00:48.594>
[00:48.750]<00:48.750>Make <00:49.062>we <00:49.375>go <00:50.000>chop <00:50.469>life <00:51.094>
[00:51.250]<00:51.250>Na <00:51.562>so <00:51.875>e <00:52.188>be <00:52.969>o <00:53.594>
[00:53.750][bg]<00:53.750>ehn <00:54.219>ehn <00:54.844>
[00:55.000][break:01:00.000]
`,
      romanised: `[ti:How You Dey]
[ar:Afro-Genie Fixture Band]
[la:pcm]
[var:romanised]
[length:01:02.500]
[by:Afro-Genie fixture generator — synthesised placeholder, not a release]

[00:08.750]<00:08.750>how <00:09.062>yoo <00:09.375>day <00:10.000>mah <00:10.312>BROH-dah <00:11.094>
[00:11.250]<00:11.250>wee <00:11.562>day <00:12.031>heeya <00:12.656>wel <00:13.125>wel <00:13.594>
[00:13.750]<00:13.750>mek <00:14.062>wee <00:14.375>goh <00:15.000>chop <00:15.469>lyf <00:16.094>
[00:16.250]<00:16.250>nah <00:16.562>soh <00:16.875>eh <00:17.188>bee <00:17.969>oh <00:18.594>
[00:18.750][bg]<00:18.750>en <00:19.219>en <00:19.844>
[00:20.000][break:00:27.500]
[00:27.500]<00:27.500>how <00:27.812>yoo <00:28.125>day <00:28.750>mah <00:29.062>BROH-dah <00:29.844>
[00:30.000]<00:30.000>wee <00:30.312>day <00:30.781>heeya <00:31.406>wel <00:31.875>wel <00:32.344>
[00:32.500]<00:32.500>mek <00:32.812>wee <00:33.125>goh <00:33.750>chop <00:34.219>lyf <00:34.844>
[00:35.000]<00:35.000>nah <00:35.312>soh <00:35.625>eh <00:35.938>bee <00:36.719>oh <00:37.344>
[00:37.500][bg]<00:37.500>en <00:37.969>en <00:38.594>
[00:38.750][break:00:43.750]
[00:43.750]<00:43.750>how <00:44.062>yoo <00:44.375>day <00:45.000>mah <00:45.312>BROH-dah <00:46.094>
[00:46.250]<00:46.250>wee <00:46.562>day <00:47.031>heeya <00:47.656>wel <00:48.125>wel <00:48.594>
[00:48.750]<00:48.750>mek <00:49.062>wee <00:49.375>goh <00:50.000>chop <00:50.469>lyf <00:51.094>
[00:51.250]<00:51.250>nah <00:51.562>soh <00:51.875>eh <00:52.188>bee <00:52.969>oh <00:53.594>
[00:53.750][bg]<00:53.750>en <00:54.219>en <00:54.844>
[00:55.000][break:01:00.000]
`,
      translated: `[ti:How You Dey]
[ar:Afro-Genie Fixture Band]
[la:eng]
[var:translated]
[length:01:02.500]
[by:Afro-Genie fixture generator — synthesised placeholder, not a release]

[00:08.750]<00:08.750>How <00:09.062>are <00:09.375>you, <00:10.000>my <00:10.312>brother? <00:11.094>
[00:11.250]<00:11.250>We <00:11.562>are <00:12.031>here <00:12.656>doing <00:13.125>fine <00:13.594>
[00:13.750]<00:13.750>Let's <00:14.375>go <00:15.000>enjoy <00:15.469>life <00:16.094>
[00:16.250]<00:16.250>That's <00:16.875>just how <00:17.188>it is <00:18.594>
[00:18.750][bg]<00:18.750>mm <00:19.219>hmm <00:19.844>
[00:20.000][break:00:27.500]
[00:27.500]<00:27.500>How <00:27.812>are <00:28.125>you, <00:28.750>my <00:29.062>brother? <00:29.844>
[00:30.000]<00:30.000>We <00:30.312>are <00:30.781>here <00:31.406>doing <00:31.875>fine <00:32.344>
[00:32.500]<00:32.500>Let's <00:33.125>go <00:33.750>enjoy <00:34.219>life <00:34.844>
[00:35.000]<00:35.000>That's <00:35.625>just how <00:35.938>it is <00:37.344>
[00:37.500][bg]<00:37.500>mm <00:37.969>hmm <00:38.594>
[00:38.750][break:00:43.750]
[00:43.750]<00:43.750>How <00:44.062>are <00:44.375>you, <00:45.000>my <00:45.312>brother? <00:46.094>
[00:46.250]<00:46.250>We <00:46.562>are <00:47.031>here <00:47.656>doing <00:48.125>fine <00:48.594>
[00:48.750]<00:48.750>Let's <00:49.375>go <00:50.000>enjoy <00:50.469>life <00:51.094>
[00:51.250]<00:51.250>That's <00:51.875>just how <00:52.188>it is <00:53.594>
[00:53.750][bg]<00:53.750>mm <00:54.219>hmm <00:54.844>
[00:55.000][break:01:00.000]
`,
    },
  },
];
